apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.tenantName }}-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.tenantName }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.tenantName }}-app
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          ports:
            - containerPort: 80
