apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tenant-{{ .tenantName }}
  namespace: tenants
spec:
  interval: 1m
  releaseName: {{ .tenantName }}-app
  chart:
    spec:
      chart: ./helm/app-chart
      sourceRef:
        kind: GitRepository
        name: saas-repo
        namespace: flux-system
  values:
    tenantName: {{ .tenantName }}
    image: {{ .image }}
